[build]
  functions = "functions"
  command = "yarn generate"

[[redirects]]
  from = "/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 301
  force = true



